# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
require 'yaml'

# This is the minimum version number required.
# Update this, if you use features of a newer version

# INSTRUCTIONS
# RUN: fastlane beta patch:false
# 

fastlane_version "1.80.0"

default_platform :ios

def get_version_number
  `/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' ../AnimeTrakr-Info.plist`.strip
end

platform :ios do

  # Store the current CFBundleVersion and CFBundleShortVersionString in the fastlane context before every lane.
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    # Increase the app version number
    patch = options[:patch]

    ensure_git_status_clean
    build_number = increment_build_number

    # Generate release notes from CHANGELOG
    changelog_filename = '../CHANGELOG.yml'
    changelog_yaml = YAML.load_file(changelog_filename)
    release_notes = changelog_yaml['upcoming'].map{ |note| note.prepend '- ' }.join("\n")

    if patch
      version = increment_version_number(bump_type: "patch")

      # Add a changelog entry for this version, 
      # yes, there is a reason for the EOS content to be on the left.
      changelog_contents = File.read(changelog_filename)
      existing_releases = changelog_contents.split('releases:').last
      this_release = changelog_yaml['upcoming'].map{ |note| note.prepend '  ' }.join("\n")
      changelog_contents = <<-EOS
upcoming:

releases:
- version: #{version}
  date: #{Time.new.strftime("%B %d %Y")}
  notes:
#{this_release}
#{existing_releases}
EOS

      File.open(changelog_filename, 'w') { |file| file.puts changelog_contents }
    end

    # Get fresh certificates
    sigh

    #match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Aozora") # Build your app - more options available
    
    slack(
      message: "New Aozora build (#{build_number}) incoming :tanabata_tree::rocket:",
      default_payloads: [],
      payload: {
        "Release Notes" => release_notes
      }
    )

    pilot(distribute_external: true, changelog: release_notes)

    clean_build_artifacts

    commit_version_bump
    if patch
      add_git_tag
    end
    push_to_git_remote

  end
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer


